return {
	Gamepasses = {
		["2x Luck"] = 250511461,
		["2x Walkspeed"] = 250511343,
		["2x Rebirth"] = 250511652,
		["3x Luck"] = 250512209,
		["2x Roll Speed"] = 251578287,
	},
	BaseRebirthRarity = 11,
	GamepassBypass = {
		["2x Luck"] = {},
		["2x Walkspeed"] = {
			201659547, -- 4igz
		},
		["2x Rebirth"] = {
			201659547,
		},
		["3x Luck"] = {},
		["2x Roll Speed"] = {},
	},
	GroupId = 15412106,
}
